export const DECREMENT = 'DECREMENT';
export const INCREMENT = 'INCREMENT';
export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';
export const SERVER_LATENCY = 'SERVER_LATENCY';
export const RECIEVE_JWT_TOKEN = 'RECIEVE_JWT_TOKEN';
