export const DECREMENT = 'DECREMENT';
export const INCREMENT = 'INCREMENT';
export const CONNECTED = 'CONNECTED';
export const DICSCONNECTED = 'DICSCONNECTED';
export const SERVER_LATENCY = 'SERVER_LATENCY';
